// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDyfFJrGroqrJacxd9ndc07R_ZCkeRno',
    appId: '1:968054122840:web:f6a6d8e1f77519f2549d2d',
    messagingSenderId: '968054122840',
    projectId: 'my-little-poney-ecbee',
    authDomain: 'my-little-poney-ecbee.firebaseapp.com',
    databaseURL: 'https://my-little-poney-ecbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-little-poney-ecbee.appspot.com',
    measurementId: 'G-VHH057P2L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUEdzbDbtzmp2mmZ6tkXWEBL5CivMl4s',
    appId: '1:968054122840:android:f7671a48622b4dad549d2d',
    messagingSenderId: '968054122840',
    projectId: 'my-little-poney-ecbee',
    databaseURL: 'https://my-little-poney-ecbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-little-poney-ecbee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpbbxcOlEnK4eBhWMOZmFeXPIbAE0ZAY',
    appId: '1:968054122840:ios:3f2388c8fdb602da549d2d',
    messagingSenderId: '968054122840',
    projectId: 'my-little-poney-ecbee',
    databaseURL: 'https://my-little-poney-ecbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-little-poney-ecbee.appspot.com',
    iosClientId: '968054122840-0gbi54k51a0b85h6susqhpkk0ee2iv2r.apps.googleusercontent.com',
    iosBundleId: 'com.mylittleponey.myLittlePoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpbbxcOlEnK4eBhWMOZmFeXPIbAE0ZAY',
    appId: '1:968054122840:ios:3f2388c8fdb602da549d2d',
    messagingSenderId: '968054122840',
    projectId: 'my-little-poney-ecbee',
    databaseURL: 'https://my-little-poney-ecbee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-little-poney-ecbee.appspot.com',
    iosClientId: '968054122840-0gbi54k51a0b85h6susqhpkk0ee2iv2r.apps.googleusercontent.com',
    iosBundleId: 'com.mylittleponey.myLittlePoney',
  );
}
